### ISSUE TITLE
error when searching older logs

### ISSUE THREAD

**Issue by da-w-xu** [justinabrahms/cribl-interview-python#1]
trying to run a search against my mac's install.log:

file:
```
dxu@K27K2J-T7Jh takehome % wc /var/log/install.log
  254466 2830139 37095255 /var/log/install.log
dxu@K27K2J-T7Jh takehome % ls -lh /var/log/install.log
-rw-r--r--@ 1 root  admin    35M Feb  4 20:24 /var/log/install.log
dxu@K27K2J-T7Jh takehome % grep 2023 /var/log/install.log | tail -n 2
2023-12-31 23:59:06-08 K27K2J-T7Jh SoftwareUpdateNotificationManager[4257]: SUOSUPowerEventObserver: System will sleep
2023-12-31 23:59:06-08 K27K2J-T7Jh softwareupdated[744]: SUOSUPowerEventObserver: System will sleep
```

curl good (searching 2024):
```
dxu@K27K2J-T7Jh takehome % curl "http://localhost:8000/logs/install.log?max_results=2&keywords=2024" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   198  100   198    0     0  89149      0 --:--:-- --:--:-- --:--:-- 99000
{
  "lines": [
    "2024-02-04 20:24:03-08 K27K2J-T7Jh suhelperd[70572]: Exiting Daemon SUHelperExitCodeNoSenders",
    "2024-02-04 20:23:58-08 K27K2J-T7Jh suhelperd[70572]: Client(pid:70570) has disconnected."
  ]
}
```

curl broken (searching 2023):
```
dxu@K27K2J-T7Jh takehome % curl "http://localhost:8000/logs/install.log?max_results=2&keywords=2023"
Internal Server Error%
```

server error when searching 2023:
```
dxu@K27K2J-T7Jh cribl-interview-python % ROOT_DIRECTORY=/var/log poetry run uvicorn cribl_python_interview.main:app --reload

INFO:     Will watch for changes in these directories: ['/Users/dxu/src/takehome/cribl-interview-python']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [72376] using StatReload
INFO:     Started server process [72380]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
{'relative': 'install.log', 'absolute': '/var/log/install.log', 'results': 2, 'keywords': ['2023']}
INFO:     127.0.0.1:52843 - "GET /logs/install.log?max_results=2&keywords=2023 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dxu/src/takehome/cribl-interview-python/cribl_python_interview/main.py", line 47, in read_file
    lines = get_relevant_lines_from_file(normalized_path, max_results, keywords)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dxu/src/takehome/cribl-interview-python/cribl_python_interview/main.py", line 147, in get_relevant_lines_from_file
    return list(itertools.islice(line_generator, max_results))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dxu/src/takehome/cribl-interview-python/cribl_python_interview/main.py", line 72, in read_file_in_reverse
    nearer_to_top_of_file = f.read(chunk_size)
                            ^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 0: invalid start byte
```

**Comment by justinabrahms** [comment]
Hey Da. Looks like we're splitting a utf-8 character in parts when we should shift one way or the other. I'll work on a patch for it. Thanks!

**Comment by justinabrahms** [comment]
Mind taking a look at the latest code? Thanks!

**Comment by da-w-xu** [comment]
ah interesting! that did fix it, i was unaware there was multibyte utf8 in there
